export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST"
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS"
export const ADMIN_REGISTER_FAIL = "ADMIN_REGISTER_FAIL"


export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL"
export const ADMIN_LOGOUT = "ADMIN_LOGOUT"

export const USER_EDITPROFILE_REQUEST = "USER_EDITPROFILE_REQUEST"
export const USER_EDITPROFILE_SUCCESS = "USER_EDITPROFILE_SUCCESS"
export const USER_EDITPROFILE_FAIL = "USER_EDITPROFILE_FAIL"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS =  "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"